<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo3ruhr"
 *
 * Auto generated by Extension Builder 2017-01-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TYPO3-Ruhr',
	'description' => 'Basis-Gerüst für die neue TYPO3 Stammtisch Ruhr Website',
	'category' => 'templates',
	'author' => 'Monika Schwarz',
	'author_email' => 'typo3@moschz.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);